// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH0xpZe-xpGxAlO-8Y_mm3WDVdvWs0-wU',
    appId: '1:764186168843:web:43f255746281eedc78810e',
    messagingSenderId: '764186168843',
    projectId: 'fir-app-tudo-list',
    authDomain: 'fir-app-tudo-list.firebaseapp.com',
    storageBucket: 'fir-app-tudo-list.appspot.com',
    measurementId: 'G-08GKB864YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtEjA0Tx05fwZz3oL-SRNuLsBrd-huLIg',
    appId: '1:764186168843:android:f4f719b85d366a2a78810e',
    messagingSenderId: '764186168843',
    projectId: 'fir-app-tudo-list',
    storageBucket: 'fir-app-tudo-list.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfDfHOTrZsmihKVzPp4txwosFJUA4BHHo',
    appId: '1:764186168843:ios:da2abc558f7612c578810e',
    messagingSenderId: '764186168843',
    projectId: 'fir-app-tudo-list',
    storageBucket: 'fir-app-tudo-list.appspot.com',
    iosBundleId: 'com.jmalvino.appTudoList',
  );
}
